/**
 * BrowserOS-XC Phase 10 — Graph Store
 *
 * In-memory singleton with optional file persistence.
 * Every mutation is idempotent (upsert + field-level merge).
 * Three export formats: JSON-LD, GraphML, Mermaid.
 *
 * Env: BROWSEROS_XC_GRAPH_DIR  (default: ./xc-graphs/)
 */

import * as fs from 'node:fs'
import * as path from 'node:path'
import type {
  APIEndpointNode,
  DependencyEdge,
  EdgeType,
  FeatureNode,
  KnowledgeGraph,
  PageNode,
  WorkflowNode,
} from './schema'
import { edgeId, nowISO, slugify } from './schema'

const GRAPH_DIR =
  process.env.BROWSEROS_XC_GRAPH_DIR ||
  path.join(process.cwd(), 'xc-graphs')

const GRAPH_JSON_PATH = path.join(GRAPH_DIR, 'graph.json')

function emptyGraph(targetUrl = ''): KnowledgeGraph {
  const now = nowISO()
  return {
    '@context': 'https://schema.org/',
    '@type': 'Dataset',
    name: `XC Knowledge Graph — ${targetUrl}`,
    description: 'Automatically generated by BrowserOS-XC MapSite',
    targetUrl,
    createdAt: now,
    updatedAt: now,
    version: 0,
    nodes: { features: {}, pages: {}, workflows: {}, apis: {} },
    edges: {},
    stats: {
      featureCount: 0,
      pageCount: 0,
      workflowCount: 0,
      apiCount: 0,
      edgeCount: 0,
      lastMutationAt: now,
      crawlDepth: 0,
      urlsVisited: [],
    },
  }
}

let _graph: KnowledgeGraph = emptyGraph()

// ── Init / Load ───────────────────────────────────────────────────────────────

export function initGraph(targetUrl?: string): KnowledgeGraph {
  if (!fs.existsSync(GRAPH_DIR)) fs.mkdirSync(GRAPH_DIR, { recursive: true })
  if (fs.existsSync(GRAPH_JSON_PATH)) {
    try {
      const raw = fs.readFileSync(GRAPH_JSON_PATH, 'utf8')
      _graph = JSON.parse(raw) as KnowledgeGraph
      if (targetUrl && _graph.targetUrl !== targetUrl) {
        _graph = emptyGraph(targetUrl)
      }
      return _graph
    } catch {
      _graph = emptyGraph(targetUrl)
    }
  } else {
    _graph = emptyGraph(targetUrl)
  }
  persistJSON()
  return _graph
}

export function getGraph(): KnowledgeGraph {
  return _graph
}

export function resetGraph(targetUrl?: string): void {
  _graph = emptyGraph(targetUrl)
  persistJSON()
}

// ── Internal helpers ──────────────────────────────────────────────────────────

function mergeObjects<T extends object>(existing: T, incoming: Partial<T>): T {
  const merged: Record<string, unknown> = { ...existing }
  for (const [k, v] of Object.entries(incoming)) {
    const cur = (existing as Record<string, unknown>)[k]
    if (v === undefined || v === null || v === '') continue
    if (Array.isArray(v) && Array.isArray(cur)) {
      merged[k] = [...new Set([...(cur as unknown[]), ...v])]
    } else if (
      v !== null && typeof v === 'object' && !Array.isArray(v) &&
      cur !== null && typeof cur === 'object' && !Array.isArray(cur)
    ) {
      merged[k] = mergeObjects(cur as object, v as object)
    } else {
      merged[k] = v
    }
  }
  return merged as T
}

function touch(): void {
  const now = nowISO()
  _graph.updatedAt = now
  _graph.version += 1
  _graph.stats.lastMutationAt = now
  recomputeStats()
}

function recomputeStats(): void {
  _graph.stats.featureCount = Object.keys(_graph.nodes.features).length
  _graph.stats.pageCount = Object.keys(_graph.nodes.pages).length
  _graph.stats.workflowCount = Object.keys(_graph.nodes.workflows).length
  _graph.stats.apiCount = Object.keys(_graph.nodes.apis).length
  _graph.stats.edgeCount = Object.keys(_graph.edges).length
}

// ── Upsert operations ─────────────────────────────────────────────────────────

export function upsertFeature(node: FeatureNode): FeatureNode {
  const existing = _graph.nodes.features[node.id]
  _graph.nodes.features[node.id] = existing
    ? mergeObjects(existing, node)
    : { ...node, discoveredAt: node.discoveredAt ?? nowISO() }
  touch()
  persistJSON()
  return _graph.nodes.features[node.id]
}

export function upsertPage(node: PageNode): PageNode {
  const existing = _graph.nodes.pages[node.id]
  _graph.nodes.pages[node.id] = existing
    ? mergeObjects(existing, node)
    : { ...node, discoveredAt: node.discoveredAt ?? nowISO() }
  if (!_graph.stats.urlsVisited.includes(node.url)) {
    _graph.stats.urlsVisited.push(node.url)
  }
  touch()
  persistJSON()
  return _graph.nodes.pages[node.id]
}

export function upsertAPI(node: APIEndpointNode): APIEndpointNode {
  const existing = _graph.nodes.apis[node.id]
  _graph.nodes.apis[node.id] = existing
    ? mergeObjects(existing, node)
    : { ...node, discoveredAt: node.discoveredAt ?? nowISO() }
  touch()
  persistJSON()
  return _graph.nodes.apis[node.id]
}

export function upsertWorkflow(node: WorkflowNode): WorkflowNode {
  const existing = _graph.nodes.workflows[node.id]
  _graph.nodes.workflows[node.id] = existing
    ? mergeObjects(existing, node)
    : { ...node, discoveredAt: node.discoveredAt ?? nowISO() }
  touch()
  persistJSON()
  return _graph.nodes.workflows[node.id]
}

export function upsertEdge(edge: DependencyEdge): DependencyEdge {
  const id = edge.id || edgeId(edge.from, edge.to, edge.type as EdgeType)
  const full: DependencyEdge = { ...edge, id, discoveredAt: edge.discoveredAt ?? nowISO() }
  const existing = _graph.edges[id]
  _graph.edges[id] = existing ? mergeObjects(existing, full) : full
  touch()
  persistJSON()
  return _graph.edges[id]
}

// ── Persist ───────────────────────────────────────────────────────────────────

function persistJSON(): void {
  try {
    if (!fs.existsSync(GRAPH_DIR)) fs.mkdirSync(GRAPH_DIR, { recursive: true })
    fs.writeFileSync(GRAPH_JSON_PATH, JSON.stringify(_graph, null, 2), 'utf8')
  } catch (e) {
    console.warn('[xc/graph-store] Could not persist JSON:', (e as Error).message)
  }
}

// ── Export: JSON-LD ───────────────────────────────────────────────────────────

export function exportJSONLD(): string {
  return JSON.stringify(_graph, null, 2)
}

// ── Export: GraphML ───────────────────────────────────────────────────────────

export function exportGraphML(): string {
  const x = (s: string) =>
    String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')

  const lines: string[] = []
  lines.push('<?xml version="1.0" encoding="UTF-8"?>')
  lines.push('<graphml xmlns="http://graphml.graphdrawing.org/graphml"')
  lines.push('  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"')
  lines.push('  xsi:schemaLocation="http://graphml.graphdrawing.org/graphml')
  lines.push('    http://graphml.graphdrawing.org/graphml/1.0/graphml.xsd">')
  lines.push('  <key id="kind" for="node" attr.name="kind" attr.type="string"/>')
  lines.push('  <key id="label" for="node" attr.name="label" attr.type="string"/>')
  lines.push('  <key id="url" for="node" attr.name="url" attr.type="string"/>')
  lines.push('  <key id="description" for="node" attr.name="description" attr.type="string"/>')
  lines.push('  <key id="etype" for="edge" attr.name="type" attr.type="string"/>')
  lines.push('  <key id="weight" for="edge" attr.name="weight" attr.type="double"/>')
  lines.push('  <graph id="G" edgedefault="directed">')

  const nodeXML = (id: string, kind: string, label: string, url: string, desc: string) =>
    [`    <node id="${x(id)}">`,
     `      <data key="kind">${x(kind)}</data>`,
     `      <data key="label">${x(label)}</data>`,
     `      <data key="url">${x(url)}</data>`,
     `      <data key="description">${x(desc)}</data>`,
     '    </node>'].join('\n')

  for (const n of Object.values(_graph.nodes.features))
    lines.push(nodeXML(n.id, 'Feature', n.name, n.pageUrl, n.description))
  for (const n of Object.values(_graph.nodes.pages))
    lines.push(nodeXML(n.id, 'Page', n.title ?? n.url, n.url, ''))
  for (const n of Object.values(_graph.nodes.workflows))
    lines.push(nodeXML(n.id, 'Workflow', n.name, '', n.description))
  for (const n of Object.values(_graph.nodes.apis))
    lines.push(nodeXML(n.id, 'API', `${n.method} ${n.urlPattern}`, n.urlPattern, ''))

  let eIdx = 0
  for (const e of Object.values(_graph.edges)) {
    lines.push(`    <edge id="e${eIdx++}" source="${x(e.from)}" target="${x(e.to)}">`)
    lines.push(`      <data key="etype">${x(e.type)}</data>`)
    if (e.weight !== undefined)
      lines.push(`      <data key="weight">${e.weight}</data>`)
    lines.push('    </edge>')
  }
  lines.push('  </graph>')
  lines.push('</graphml>')
  return lines.join('\n')
}

// ── Export: Mermaid ───────────────────────────────────────────────────────────

export function exportMermaid(): string {
  const mid = (id: string) => id.replace(/[^a-zA-Z0-9_]/g, '_').replace(/^_+/, 'N')
  const ml = (t: string) => t.replace(/"/g, "'")

  const lines: string[] = []
  lines.push('```mermaid')
  lines.push('flowchart TD')
  lines.push('')

  lines.push('  %% ── Pages ──')
  for (const n of Object.values(_graph.nodes.pages))
    lines.push(`  ${mid(n.id)}["📄 ${ml(n.title ?? n.url)}"]`)

  lines.push('')
  lines.push('  %% ── Features ──')
  for (const n of Object.values(_graph.nodes.features)) {
    const flag = n.featureFlag ? ` 🚩${n.featureFlag}` : ''
    const auth = n.authRequired ? ' 🔒' : ''
    lines.push(`  ${mid(n.id)}(["✨ ${ml(n.name)}${flag}${auth}"])`)
  }

  lines.push('')
  lines.push('  %% ── Workflows ──')
  for (const n of Object.values(_graph.nodes.workflows))
    lines.push(`  ${mid(n.id)}{{"⚙️ ${ml(n.name)}"}}`)

  lines.push('')
  lines.push('  %% ── API Endpoints ──')
  for (const n of Object.values(_graph.nodes.apis))
    lines.push(`  ${mid(n.id)}[("🔌 ${ml(n.method + ' ' + n.urlPattern)}")]`)

  lines.push('')
  lines.push('  %% ── Edges ──')
  const arrowStyle: Record<string, string> = {
    requires:     '-.->', triggers: '-->',
    navigates_to: '==>', calls_api: '--o',
    renders_on:   '---', part_of: '-.->', guarded_by: '-. guards .->', depends_on: '-.->' }
  for (const e of Object.values(_graph.edges)) {
    const arrow = arrowStyle[e.type] ?? '-->'
    const lbl = e.label ? `|"${ml(e.label)}"|` : `|${e.type}|`
    lines.push(`  ${mid(e.from)} ${arrow} ${lbl} ${mid(e.to)}`)
  }

  lines.push('')
  lines.push(`  %% Generated by BrowserOS-XC  v${_graph.version}  ${_graph.updatedAt}`)
  lines.push('```')
  return lines.join('\n')
}

// ── Persist all formats ───────────────────────────────────────────────────────

export function persistAll(): { jsonPath: string; graphmlPath: string; mdPath: string } {
  if (!fs.existsSync(GRAPH_DIR)) fs.mkdirSync(GRAPH_DIR, { recursive: true })
  const graphmlPath = path.join(GRAPH_DIR, 'graph.graphml')
  const mdPath = path.join(GRAPH_DIR, 'graph.md')
  fs.writeFileSync(GRAPH_JSON_PATH, exportJSONLD(), 'utf8')
  fs.writeFileSync(graphmlPath, exportGraphML(), 'utf8')
  fs.writeFileSync(mdPath, exportMermaid(), 'utf8')
  return { jsonPath: GRAPH_JSON_PATH, graphmlPath, mdPath }
}

// ── Keyword search ────────────────────────────────────────────────────────────

type AnyNode = FeatureNode | PageNode | WorkflowNode | APIEndpointNode

export function searchNodes(query: string): AnyNode[] {
  const q = query.toLowerCase()
  const all: AnyNode[] = [
    ...Object.values(_graph.nodes.features),
    ...Object.values(_graph.nodes.pages),
    ...Object.values(_graph.nodes.workflows),
    ...Object.values(_graph.nodes.apis),
  ]
  return all.filter((n) => JSON.stringify(n).toLowerCase().includes(q))
}

// ── Summary ───────────────────────────────────────────────────────────────────

export function buildSummary(): string {
  const s = _graph.stats
  const lines: string[] = []
  lines.push(`# BrowserOS-XC Knowledge Graph — v${_graph.version}`)
  lines.push(`**Target:** ${_graph.targetUrl}`)
  lines.push(`**Last updated:** ${_graph.updatedAt}`)
  lines.push('')
  lines.push('## Stats')
  lines.push(`- 📄 Pages crawled: **${s.pageCount}** (${s.urlsVisited.length} unique URLs)`)
  lines.push(`- ✨ Features mapped: **${s.featureCount}**`)
  lines.push(`- ⚙️  Workflows documented: **${s.workflowCount}**`)
  lines.push(`- 🔌 API endpoints observed: **${s.apiCount}**`)
  lines.push(`- 🔗 Graph edges: **${s.edgeCount}**`)
  lines.push('')
  if (s.featureCount > 0) {
    lines.push('## Features')
    for (const f of Object.values(_graph.nodes.features)) {
      const auth = f.authRequired ? ' [auth]' : ''
      const flag = f.featureFlag ? ` [flag:${f.featureFlag}]` : ''
      lines.push(`- **${f.name}**${auth}${flag}: ${f.description}`)
    }
    lines.push('')
  }
  if (s.workflowCount > 0) {
    lines.push('## Workflows')
    for (const w of Object.values(_graph.nodes.workflows))
      lines.push(`- **${w.name}** (${w.steps.length} steps, ${w.triggeredAPIs.length} APIs)`)
    lines.push('')
  }
  if (s.apiCount > 0) {
    lines.push('## API Endpoints')
    for (const a of Object.values(_graph.nodes.apis))
      lines.push(`- \`${a.method} ${a.urlPattern}\``)
    lines.push('')
  }
  return lines.join('\n')
}
